story/landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
    path('', views.landingpage, name='landingpage'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('gallery/', views.gallery, name='gallery'),
]

story/story3/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

story/landingpage/models.py
from django.db import models

# Create your models here.

story/landingpage/views.py
from django.shortcuts import render

# Create your views here.

def landingpage(request):
    return render(request, 'story3_landing.html')

def about(request):
    return render(request, 'story3_about.html')

def profile(request):
    return render(request, 'story3_profile.html')

def gallery(request):
    return render(request, 'story3_gallery.html')

def portfolio(request):
    return render(request, 'story3_portofolio.html')

story/landingpage/templates/story3_about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>About</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel='icon' href='fh.png' type='image/x-icon'/ >
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <!-- Connect HTML with CSS file -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/story3_about.css' %}">

   <!-- Set Montserrat from Google Font, as the main font -->
   <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>

<body>
	<div class="face">
		<nav class="navbar navbar-default navbar-fixed-top">
 			<div class="container-fluid">
    			<div class="navbar-header">
      				<a class="navbar-brand" href="story3_landing.html"><img src="fh.png" width="80" height="80"></a>
    			</div>
    			<ul class="nav navbar-nav">
      			<li class="active"><a href="#"><img src="about_act.png" width="75" height="75"></a></li>
      			<li><a href="story3_profile.html"><img src="prof_pas.png" width="75" height="75"></a></li>
      			<li><a href="story3_portofolio.html"><img src="port_pas.png" width="75" height="75"></a></li>
      			<li><a href="story3_gallery.html"><img src="gal_pas.png" width="75" height="75"></a></li>
    			</ul>
  			</div>
</nav>
		<h3><br></h3>
		<img src="q.png" height="50" width="50">
		
		<h3>ABOUT ME</h3>
		<p>Greetings, i am Ferdinand, from Universitas Indonesia. <br>I’m pursuing my bachelor degree in Information System field. <br>Technology, writing and art are fields that i'm really into. <br>I was born at Jakarta, January 13th 2001. I lived in Central Jakarta. <br>I'd love to write, do the lettering and crossword in my sparetime.</p>
	<div class="images">
		<a href="tel:+6287880069007" ><img src="phone.png" height="170" width="170"></a>
		<img height="100" width="100">
		<a href="mailto:ferdiihfz@gmail.com?Subject=Hello" ><img src="mail.png"  height="170" width="170"></a>
		<br><br><br><br>
	</div>

		<img src="q.png" height="50" width="50" >

	<h3>SOCIAL MEDIA</h3>
	<div class="images">
		<a href="https://www.linkedin.com/in/ferdinandhf/" target="_blank"><img src="link.png"  height="100" width="100">
			<img height="50" width="50">
		<a href="https://www.instagram.com/ferrrdos" target="_blank"><img src="ig.png"  height="100" width="100">
			<img height="50" width="50">
		<a href="https://www.twitter.com/wtferdos" target="_blank"><img src="tw.png"  height="100" width="100">
			<img height="50" width="50">
		<a href="https://id.pinterest.com/ferdiihfz/" target="_blank"><img src="pin.png"  height="100" width="100">
	</div>

	</div>
</body>

story/landingpage/templates/story3_gallery.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>About</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel='icon' href='fh.png' type='image/x-icon'/ >
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <!-- Connect HTML with CSS file -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/story3_about.css' %}">

   <!-- Set Montserrat from Google Font, as the main font -->
   <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>

<body>
	<div class="face">
		<nav class="navbar navbar-default navbar-fixed-top">
 			<div class="container-fluid">
    			<div class="navbar-header">
      				<a class="navbar-brand" href="story3_landing.html"><img src="fh.png" width="80" height="80"></a>
    			</div>
    			<ul class="nav navbar-nav">
      			<li><a href="story3_about.html"><img src="about_pas.png" width="75" height="75"></a></li>
      			<li><a href="story3_profile.html"><img src="prof_pas.png" width="75" height="75"></a></li>
      			<li><a href="story3_portofolio.html"><img src="port_pas.png" width="75" height="75"></a></li>
      			<li class="active"><a href="#"><img src="gal_act.png" width="75" height="75"></a></li>
    			</ul>
  			</div>
</nav>
		<h3><br></h3>
		<img src="q.png" height="50" width="50">
		
		<h3>GALLERY</h3>
		<div class="container-fluid">
		  <div class="row">
		    <div class="col-sm-6"><img src="hums.jpg" height="50%" width="70%"></div>
		    <div class="col-sm-6"><img src="hums2.jpg" height="50%" width="70%"></div>
		  </div>
    </div>
	</div>
</body>

story/landingpage/templates/story3_landing.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Ferdii's Page</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel='icon' href='fh.png' type='image/x-icon'/ >
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <!-- Connect HTML with CSS file -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/story3_about.css' %}">

   <!-- Set Montserrat from Google Font, as the main font -->
   <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>

<body class="only">
		<div class="frontpage">
		<p>
			<br>
			<br>
		</p>
		<h3 class="landing">Now, you’re landing at the profile of<br><br></h3>
		<div class="headprof">
		<img src="https://quanta2018.com/Biodata/img/112.png" height="275" width="275">
			</div>
		<h2 class="front">FERDINAND HANIF FAOZI</h2>

		<a href="story3_about.html" class="btn btn-lg active see-more" role="button" aria-pressed="true">SEE MORE</a>
		<br><br>
	</div>
</body>

story/landingpage/templates/story3_portofolio.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>About</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel='icon' href='fh.png' type='image/x-icon'/ >
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <!-- Connect HTML with CSS file -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/story3_about.css' %}">

   <!-- Set Montserrat from Google Font, as the main font -->
   <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>

<body>
	<div class="face">
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="menu">
 			<div class="container-fluid menubar">
    			<div class="navbar-header">
      				<a class="navbar-brand" href="story3_landing.html"><img src="fh.png" width="80" height="80"></a>
    			</div>
    			<ul class="nav navbar-nav">
      			<li><a href="story3_about.html"><img src="about_pas.png" width="75" height="75"></a></li>
      			<li><a href="story3_profile.html"><img src="prof_pas.png" width="75" height="75"></a></li>
      			<li class="active"><a href="#"><img src="port_act.png" width="75" height="75"></a></li>
      			<li><a href="story3_gallery.html"><img src="gal_pas.png" width="75" height="75"></a></li>
    			</ul>
    			</div>
  			</div>
</nav>
		<h3><br></h3>
		<img src="q.png" height="50" width="50" >

		<h3>PORTFOLIO</h3>
			<br>
				<div class="container-fluid">
				  <div class="row">
				    <div class="col-sm-4">
				    	<a href="https://www.figma.com/proto/g12iDr8uEg97fl4hb0JxEmBx/Untitled?node-id=3%3A3&scaling=scale-down" target="_blank"><img src="uiux.png" height="225" width="225" ><p>UI/UX Design</p></a>
				    </div>
				    <div class="col-sm-4">
				    	<a href="https://drive.google.com/drive/folders/1CNcUdvyhGt1dMOQpxNvtNcdcSh1m0xgd" target="_blank"><img src="visdes.png" height="225" width="225"><p>Visual Design</p></a>
				    </div>
				    <div class="col-sm-4">
				    	<a href="https://drive.google.com/drive/folders/17NDsAu24QrmT9KT3tMZqdC52meAjfxDS" target="_blank"><img src="write.png" height="225" width="225" ><p>Copywriting</p></a>
				    </div>
				  </div>
				</div>
		<br><br>

</body>

story/landingpage/templates/story3_profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>About</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel='icon' href='fh.png' type='image/x-icon'/ >
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <!-- Connect HTML with CSS file -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/story3_about.css' %}">

   <!-- Set Montserrat from Google Font, as the main font -->
   <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>

<body>
	<div class="face">
		<nav class="navbar navbar-default navbar-fixed-top">
 			<div class="container-fluid">
    			<div class="navbar-header">
      				<a class="navbar-brand" href="story3_landing.html"><img src="fh.png" width="80" height="80"></a>
    			</div>
    			<ul class="nav navbar-nav">
      			<li><a href="{% url 'landingpage:about' %}"><img src="{% static 'images/about_pas.png' %}" width="75" height="75"></a></li>
      			<li class="active"><a href="#"><img src="{% static 'images/prof_act.png' %}" width="75" height="75"></a></li>
      			<li><a href="{% url 'landingpage:portfolio' %}"><img src="{% static 'images/port_pas.png' %}" width="75" height="75"></a></li>
            <li><a href="{% url 'landingpage:gallery' %}"><img src="{% static 'images/gal_pas.png' %}" width="75" height="75"></a></li>
    			</ul>
  			</div>
</nav>

    <h3><br></h3>
    <img src="{% static 'images/q.png' %}" height="50" width="50" >
    <h3>EDUCATION</h3>
		
		<div class="container-fluid">
		  <div class="row">
		    <div class="col-sm-6"><img src="{% static 'images/ui.png' %}" height="150" width="150">
          <p class="titledescription">Universitas Indonesia</p>
          <p class="description">Faculty of Computer Science,<br>Information System Degree<br>(2018 - 2022)</p>
        </div>

		    <div class="col-sm-6"><img src="{% static 'images/jpn.png' %}" height="150" width="170" >
          <p class="titledescription">SMAN 78 Jakarta</p>
          <p class="description">Math and Natural <br>Science Program<br>(2015-2018)</p>
        </div>

		  </div>
    </div>

    <img src="{% static 'images/q.png' %}" height="50" width="50" >
    <h3>EXPERIENCE</h3>
    <p class="year">year of 2019</p>
    <br>
    <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6">
             <p class="exptitle">COMPFEST 11</p>
             <p class="expdescription">as Staff of Editorial Marketing</p>
             <p class="description">Jan 2019 - present.</p>
            </div>

            <div class="col-sm-6">
              <p class="exptitle">Wisuda Genap 2019</p>
              <p class="expdescription">as the PIC of Creative</p>
              <p class="description">May 2019 - Sep 2019</p>
            </div>
          </div>

          <br> <br>

          <div class="row">
            <div class="col-sm-6">
             <p class="exptitle">BEM Fasilkom UI</p>
             <p class="expdescription">as Staff of Public Relations Bureau</p>
             <p class="description">Feb 2019 - present.</p>
            </div>
            
            <div class="col-sm-6">
              <p class="exptitle">Computers Get Together</p>
              <p class="expdescription">as Staff of Decoration Div.</p>
              <p class="description">Feb 2019 - May 2019</p>
            </div>
          </div>

          <br> <br>

          <div class="row">
            <div class="col-sm-6">
             <p class="exptitle">OH Fasilkom UI</p>
             <p class="expdescription">as the Vice PIC of Public Relations Bureau</p>
             <p class="description">May 2019 - present.</p>
            </div>
            
            <div class="col-sm-6">
              <p class="exptitle">Wisuda Ganjil 2019</p>
              <p class="expdescription">as Staff of Creative</p>
              <p class="description">Dec 2018 - Feb 2019</p>
            </div>
          </div>

        </div>
        <h3><br></h3>
        
      <img src="{% static 'images/q.png' %}" height="50" width="50" >
    <h3>SKILLS</h3>

	</div>
</body>